function res=g2(q0,~)
% Cette fonction calcul g (membre de droite de ED) pour le cas 1
% avec
%	q0	:   conditions initiales [q(t0)]
%	t0	:   intervalle de temps initial
%	w0	:   la vitesse angulaire initiale, elle est supposée constante
[H, ~] = getConstantesProbleme();
[~, m] = getDonneesBalle();

res = [ ... 
    1/m*(H*sqrt(q0(1)^2+q0(2)^2+q0(3)^2)*q0(1)) ...
    1/m*(H*sqrt(q0(1)^2+q0(2)^2+q0(3)^2)*q0(2)) ...
    1/m*(H*sqrt(q0(1)^2+q0(2)^2+q0(3)^2)*q0(3) + (-9.8)*m) ...
    q0(1) ...
    q0(2) ...
    q0(3) ...
];
