function res=getMatriceGRoulement(q0)
% Cette fonction calcul g (membre de droite de ED) pour le cas 1,
% c est a dire lorsque l'auto roule et ne glisse pas.
% avec
%	q0	:   conditions initiales [q(t0)]

res = [ ... 
    0 ...
    0 ...
    0 ...
    q0(1) ...
    q0(2) ...
    q0(3) ...
];
